### PR TITLE
Clacladev/player errors

### LINKED ISSUE #167: Player should error when content is token gated or inactive
Currently, when the player is using an HLS URL that contains either content that has not begun yet or the user is not using a signed URL for token-gated content, the player will display an infinite spinner. This gives the impression that the content will begin shortly; when it doesn't, the user assumes that something has gone wrong. 

An ideal solution looks like:
- When a stream has not started yet or is inactive, the player does not display the spinner -- just an empty player. 
- When a stream has started, but it isn't displayed yet or is pending, the spinner is shown. 
- If the viewer is not using a signed URL when a stream has a playback policy of `signed`, "It looks like you don't have permission to view this content" 
- [ADDED 12/12/22]: Report via telemetry when errors occur

_EDITED by @0xcadams_:
- IPFS auto playback while an asset is waiting to be uploaded to studio and the transcoded version played back - see [discord chat here](https://discord.com/channels/423160867534929930/1042472815586197554/1046893233424302141)

Future iterations might include:
- Allowing users to configure their own error messages

### PR DESCRIPTION
**Pull request by clacladev**
## Description
Introduced the offline and private livestream player errors.

Fixes #167 

## Additional Information
- To be evaluated how much more customisation we want to provide on our default errors (**Note**: there will be a followup ticket to add deeper customisation, replacing completely the the error view)
- TBD if we're adding the same errors also for React Native and if so, if we're doing it in the same ticket

## Screenshots
Screenshot 2022-12-19 at 13 26 08
Screenshot 2022-12-19 at 13 26 35
Screenshot 2022-12-20 at 17 10 17

### CODE REVIEW

File: packages/react/src/components/media/controls/images/OfflineStreamImage.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
+const OfflineStreamImage = () => (
+  <div
+    dangerouslySetInnerHTML={{
```
Comment (0xcadams) [inline packages/react/src/components/media/controls/images/OfflineStreamImage.tsx]: We should replace this with just the svg element content, instead of using `dangerouslySetInnerHTML`

Comment (0xcadams) [reply packages/react/src/components/media/controls/images/OfflineStreamImage.tsx]:
```tsx
const OfflineStreamImage = () => (<svg>...</svg>)
```

File: packages/react/src/components/media/controls/images/PrivateStreamImage.tsx [hunk 2]
```diff
@@ -0,0 +1,33 @@
+const PrivateStreamImage = () => (
+  <div
+    dangerouslySetInnerHTML={{
```
Comment (0xcadams) [inline packages/react/src/components/media/controls/images/PrivateStreamImage.tsx]: Same replacing here

File: packages/react/src/components/media/players/HlsPlayer.tsx [hunk 3]
```diff
@@ -68,7 +70,11 @@ export const HlsPlayer = React.forwardRef<HTMLVideoElement, HlsPlayerProps>(
       const element = store.getState()._element;
       if (element && canUseHlsjs && !canPlayAppleMpeg && src.src) {
         const onError = (error: HlsError) => {
-          console.warn(error.response?.data.toString());
+          const cleanError = new Error(error.response?.data.toString());
+          if (isAccessControlError(cleanError)) {
+            onAccessControlError?.(cleanError);
```
Comment (0xcadams) [inline packages/react/src/components/media/players/HlsPlayer.tsx:75]: We will need to test this flow on Safari as well - my hunch is that we will need to hook into the native Safari error callback too

File: packages/core-react/src/components/player/useSourceMimeTyped.tsx [hunk 4]
```diff
@@ -56,6 +55,13 @@ export const useSourceMimeTyped = <TElement, TPoster>({
     onAssetStatusChange,
   });
 
+  const [isStreamOffline, setIsStreamOffline] = React.useState<boolean>(false);
+
+  React.useEffect(() => {
```
Comment (0xcadams) [inline packages/core-react/src/components/player/useSourceMimeTyped.tsx]: We could use a `useMemo` here for simplicity - something like

```suggestion
const isStreamOffline = React.useMemo(() => playbackInfo?.type === 'live' && !playbackInfo?.meta?.live);
```

**Review by 0xcadams — CHANGES_REQUESTED** [review]
This looks great! A few changes I think we could make.

Also, I think we'll need to update `usePlaybackInfoOrImport` to continue to refetch when the stream is offline. Currently, it will refetch until it gets a valid playbackInfo response. But if the stream is offline, it won't continue polling. We should change it to poll for the stream to be live again.

File: packages/react/src/components/media/controls/images/OfflineStreamImage.tsx (hunk 1 above)
Comment (clacladev) [reply packages/react/src/components/media/controls/images/OfflineStreamImage.tsx]: I wrapped this this way because just copying and pasting the svg, then we have react asking to rename some properties (`fill-rule` to `fillRule` etc) otherwise it will throw an error. Anyway, I have now renamed all the props. Which we have to redo in case we update the image.

File: packages/react/src/components/media/players/HlsPlayer.tsx (hunk 3 above)
Comment (clacladev) [reply packages/react/src/components/media/players/HlsPlayer.tsx:75]: Retesting I realise that the Offline error works also on Safari (using the video html element). But the Private error that was HlsPlayer specific. I will try to hook up error management to the video element too.

File: packages/core-react/src/components/player/useSourceMimeTyped.tsx (hunk 4 above)
Comment (clacladev) [reply packages/core-react/src/components/player/useSourceMimeTyped.tsx]: Good point, it's just simpler this way

File: packages/react/src/components/media/players/HlsPlayer.tsx (hunk 3 above)
Comment (clacladev) [reply packages/react/src/components/media/players/HlsPlayer.tsx:75]: @0xcadams You can check the `packages/react/src/components/media/Player.tsx` where I added error capture, but it does not work as expected.

First, there is error capture on the video element, which does not return enough information to understand what is the error about.
Second, there is error capture on the video's source element. This one is never triggered instead...

Can you look into this issue? Maybe based on your experience you know how to squeeze info out of the video/source elements...

Comment (0xcadams) [reply packages/react/src/components/media/players/HlsPlayer.tsx:75]: Yeah I can look into that, I also don't know how much info we can get from the native video player in Safari. We also have a lot of playback issues with Safari, so I'm actually leaning towards using HLS.js in Safari to make our Player easier to maintain. I think we could merge this without Safari and then follow up separately to move Safari playback to use HLS.js.

Comment (0xcadams) [reply packages/react/src/components/media/players/HlsPlayer.tsx:75]: https://github.com/livepeer/livepeer.js/issues/222

Comment (clacladev) [reply packages/react/src/components/media/players/HlsPlayer.tsx:75]: I agree with you that using HLS.js always will simplify maintenance of the player. Great!

**Comment by clacladev** [comment]
Hey @0xcadams do you want to give it a final review?

**Review by 0xcadams — APPROVED** [review]
🚢

**Comment by 0xcadams** [comment]
Great work on this! Looks super clean 🧽
