### PR TITLE
Fix for Nodejs File

### LINKED ISSUE #254: [bug] Create asset explodes in node.js
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.1.2

### Current Behavior

Trying to upload a file fails with the following exception:
```
fatal error: File is not defined
ReferenceError: File is not defined
    at /home/victorges/workspace/src/github.com/livepeer/decrypter/node_modules/@livepeer/core/providers/studio/dist/livepeer-core-providers-studio.
cjs.dev.js:215:35
    at new Promise (<anonymous>)
    at /home/victorges/workspace/src/github.com/livepeer/decrypter/node_modules/@livepeer/core/providers/studio/dist/livepeer-core-providers-studio.
cjs.dev.js:209:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async StudioLivepeerProvider.createAsset (/home/victorges/workspace/src/github.com/livepeer/decrypter/node_modules/@livepeer/core/providers/$
tudio/dist/livepeer-core-providers-studio.cjs.dev.js:186:29)
```

I could work around with
```
class FakeFile {}
global.File = FakeFile as any
```
but that's not something we should force our users to do.

The fix should be relatively simple, just changing this line:
https://github.com/livepeer/livepeer.js/blob/686fb5178a5746210cc16f1efb77f2c1273f4527/packages/core/src/providers/studio/index.ts#L189

to check if `File` is globally defined before using it.

### Expected Behavior

No error =P

### Steps To Reproduce

Call `createAsset` in node.js

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by 0xcadams**
## Description

Fixed Node.js issue with `File` not being defined globally.

Closes https://github.com/livepeer/livepeer.js/issues/254

### CODE REVIEW

File: packages/core/src/providers/studio/index.ts [hunk 1]
```diff
@@ -186,7 +186,7 @@ export class StudioLivepeerProvider extends BaseLivepeerProvider {
                 metadata: {
                   id: assetId,
                 },
-                ...((source as CreateAssetSourceFile) instanceof File
+                ...((source as unknown as File).name
```
Comment (victorges) [inline packages/core/src/providers/studio/index.ts]: I don't think it needs to change, but FTR I believe an alternative would be
```suggestion
                ...(typeof File !== 'undefined' && source instanceof File)
```

That's what I had done in the legacy `video-nft` sdk, just found it: https://github.com/livepeer/video-nft/blob/main/src/api.ts#L229

**Review by victorges — APPROVED** [review]
LGTM!

File: packages/core/src/providers/studio/index.ts (hunk 1 above)
Comment (0xcadams) [reply packages/core/src/providers/studio/index.ts]: Yeah I like that!
